version: '3'

services:
  db:
    image: mariadb:10.6.16
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes: 
      - db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  wordpress:
    depends_on: 
      - db
    image: wordpress:php8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    environment:
      - NGINX_SERVER_NAME=$NGINX_SERVER_NAME
    networks:
      - app-network
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - wp_data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email mike@blueleopard.digital --agree-tos --no-eff-email --staging -d $HOST
    logging:
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  wp_data:
  db_data:
  certbot-etc:
  certbot-var:

networks:
  app-network:
